name: Build Thesis PDF

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install GitHub CLI
        run: sudo apt install gh -y

      - name: Install Pygments
        run: pip install Pygments

      - name: Prepare minted directory
        run: mkdir -p build/_minted-thesis

      - name: Check pygmentize
        run: which pygmentize

      - name: Install TeX requirements
        run: sudo apt-get update && sudo apt-get install -y texlive-full

      - name: Run Make setup
        run: make setup

      - name: Build PDF
        run: make build
        shell: bash

      - name: Bump version from commits
        id: semver
        uses: issue-ops/semver@v0.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch

      - name: Push new tag
        run: |
          git tag ${{ steps.semver.outputs.new_version }}
          git push origin ${{ steps.semver.outputs.new_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Draft release with commits
        uses: release-drafter/release-drafter@v5
        with:
          version: ${{ steps.semver.outputs.new_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get draft release body
        id: get_body
        run: |
          body=$(gh release view $(gh release list --draft --json tagName -q '.[0].tagName') --json body -q '.body')
          echo "body=$body" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
