name: Build Thesis PDF

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt install gh -y

      - name: Install Pygments
        run: pip install Pygments

      - name: Prepare minted directory
        run: mkdir -p build/_minted-thesis

      - name: Add pygmentize to PATH
        run: echo "/opt/hostedtoolcache/Python/3.11.14/x64/bin" >> $GITHUB_PATH


      - name: Install TeX requirements
        run: sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra

      - name: Run Make setup
        run: make setup

      - name: Build PDF
        run: make build
        shell: bash

      - name: Auto Generate Next Release Tag by Date
        id: generate_tag
        uses: alexvingg/next-release-tag@v1.0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push new tag
        run: |
          git tag ${{ steps.generate_tag.outputs.release_tag }}
          git push origin ${{ steps.generate_tag.outputs.release_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Draft release with commits
        uses: release-drafter/release-drafter@v5
        with:
          version: ${{ steps.generate_tag.outputs.release_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get draft release body
        id: get_body
        run: |
          body=$(gh release view $(gh release list --draft --json tagName -q '.[0].tagName') --json body -q '.body')
          echo "body=$body" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Github release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.generate_tag.outputs.next_release_tag }}
          body: ${{ steps.get_body.outputs.body }}
          files: build/thesis.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
